"""Reviewer-session telemetry: server-side receiver contract + widget snippet.

Implements the guide section 7 pattern (model-invisible bridge exfil) as
clean-room code: validate events, assemble per-session streams, emit the
reviewer timeline. The widget snippet is generated, not vendored.
"""
from __future__ import annotations

import json
import time
import uuid
from dataclasses import dataclass, field

EVENTS = {"connected", "tool_listed", "tool_selected", "executed", "rendered",
          "widget_error", "result", "loaded", "visible", "hidden", "closed",
          "error", "interaction"}

REQUIRED_CTX = {"host", "theme", "client"}


@dataclass
class SessionStream:
    session_id: str
    events: list[dict] = field(default_factory=list)

    def append(self, event: dict) -> dict:
        kind = event.get("event")
        if kind not in EVENTS:
            return {"ok": False, "error": f"unknown event {kind!r}"}
        ctx = event.get("context", {}) or {}
        missing = sorted(REQUIRED_CTX - set(ctx))
        if missing:
            return {"ok": False, "error": f"missing context {missing}"}
        self.events.append({**event, "t": event.get("t", time.time())})
        return {"ok": True, "n": len(self.events)}

    def reviewer_timeline(self) -> list[str]:
        return [f"{e.get('t', 0):.0f} {e.get('event')}" for e in self.events]


class Receiver:
    """In-memory receiver; back with SQLite/Postgres in production."""

    def __init__(self) -> None:
        self.sessions: dict[str, SessionStream] = {}

    def ingest(self, payload: dict) -> dict:
        sid = payload.get("session_id") or f"sess_{uuid.uuid4().hex[:12]}"
        stream = self.sessions.setdefault(sid, SessionStream(session_id=sid))
        res = stream.append(payload)
        return {"session_id": sid, **res}

    def failures(self, session_id: str) -> list[dict]:
        s = self.sessions.get(session_id)
        if not s:
            return []
        return [e for e in s.events if e.get("event") in ("widget_error", "error")]


WIDGET_SNIPPET = """// AgentCom telemetry snippet (generated by runtime/telemetry.py).
// Fire-and-forget through the model-invisible record_signal tool; direct
// fetch only to origins declared in _meta.ui.csp.connectDomains.
(function () {
  var SID = "sess_" + Math.random().toString(36).slice(2, 14);
  function ctx() {
    return { host: detectHost(), theme: document.documentElement.dataset.theme || "unknown",
             client: navigator.userAgent.slice(0, 80) };
  }
  function detectHost() {
    if (window.openai && window.openai.callTool) return "chatgpt";
    return "generic";
  }
  function send(event, data) {
    var payload = { session_id: SID, event: event, context: ctx(), data: data || {} };
    try {
      if (detectHost() === "chatgpt" && window.openai.callTool) {
        window.openai.callTool({ name: "record_signal", arguments: payload });
      } else if (window.parent !== window) {
        window.parent.postMessage({ type: "tools/call", tool: "record_signal", payload: payload }, "*");
      }
    } catch (e) { /* telemetry never breaks the app */ }
    try {
      if (navigator.sendBeacon) navigator.sendBeacon(
        "__TELEMETRY_URL__", new Blob([JSON.stringify(payload)], { type: "application/json" }));
    } catch (e) { /* fire-and-forget */ }
  }
  window.AgentComSignal = { send: send, session: SID };
  send("loaded", {});
  document.addEventListener("visibilitychange", function () {
    send(document.hidden ? "hidden" : "visible", {});
  });
})();
"""


def render_snippet(telemetry_url: str) -> str:
    return WIDGET_SNIPPET.replace("__TELEMETRY_URL__", telemetry_url)


if __name__ == "__main__":
    r = Receiver()
    print(json.dumps(r.ingest({"event": "connected",
                               "context": {"host": "chatgpt", "theme": "dark", "client": "demo"}}), indent=2))
